/**
 * Available cap actions for a team.
 *
 * Returns the list of cap-related moves a team can make right now, given
 * their current payroll + apron status. The negotiation/UI layer uses this
 * to render affordances ("Use MLE", "Match RFA offer", etc.) and to gate
 * actions that would push the team over a hard cap.
 *
 * v1 scope:
 *   - Sign with cap room (if under cap)
 *   - Room exception (if under cap, after using room)
 *   - Non-tax MLE (over cap, under first apron)
 *   - Tax MLE (in tax, under first apron)
 *   - Taxpayer MLE (in first apron, blocked by second apron)
 *   - Bi-Annual Exception (under first apron)
 *   - Veteran minimum (always)
 *   - Waive-and-stretch (always, if has releasable contracts)
 *
 * v2 deferred:
 *   - Trade-pending TPE (Traded Player Exception) — generated by trades,
 *     usable for up to 1 year. Requires trade history tracking.
 *   - Sign-and-trade arrangements — multi-team coordination + BYC math.
 *   - Hard-cap activation tracking (sign-and-trade acquisition, MLE use,
 *     etc.) that affects future-action availability.
 *   - BAE every-other-year enforcement (requires history).
 */

import type { TeamId } from '@bs/core/adapter';
import type { BasketballPlayer } from '../types';
import { basketballTeamCapStatus, basketballSalaryCap, minimumSalary } from './capRules';

// ===========================================================================
// Approximated exception amounts (% of cap)
// ===========================================================================

/** Non-tax Mid-Level: real 2026-27 $15.04M on a $164.96M cap ≈ 9.1% of cap. */
const NON_TAX_MLE_PCT = 0.094;
/** Tax MLE (over tax line, under first apron): real 2026-27 $6.06M ≈ 3.68% of cap. */
const TAX_MLE_PCT = 0.0368;
/** Taxpayer MLE (first apron team): same $6.06M, but use blocked by 2nd apron. */
const TAXPAYER_MLE_PCT = 0.0368;
/** Bi-Annual Exception: real 2026-27 $5.48M ≈ 3.32% of cap. */
const BAE_PCT = 0.0332;
/** Room Exception: real 2026-27 ~$8.8M ≈ 5.33% of cap. */
const ROOM_EXCEPTION_PCT = 0.0533;

// ===========================================================================
// Public types
// ===========================================================================

export interface BasketballCapAction {
  /** Stable machine identifier — UI keys off this. */
  id: string;
  /** Display label shown to the user. */
  label: string;
  /** Tooltip / longer description explaining what the action does. */
  description: string;
  /** True if usable in the team's current state. */
  available: boolean;
  /** When available=false, why. Surfaces in UI as a disabled-button hint. */
  blockedReason?: string;
  /** Approximate dollar amount this action grants (for sortable display). */
  approxAmount?: number;
}

// ===========================================================================
// Main entry
// ===========================================================================

export function basketballAvailableCapActions(
  teamId: TeamId,
  players: BasketballPlayer[],
  season: number,
  /** Dead money on the team's books — counts against the cap/aprons. */
  extraPayroll = 0,
): BasketballCapAction[] {
  // Only count players on THIS team
  const teamPlayers = players.filter(p => p.rosterSlot?.teamId === teamId);
  const status = basketballTeamCapStatus(teamPlayers, season, extraPayroll);
  const cap = basketballSalaryCap(season);

  const actions: BasketballCapAction[] = [];

  // --- Cap-room signing path (team under cap) ---
  if (status.capRoom > 0) {
    actions.push({
      id: 'sign_with_cap_room',
      label: `Sign with cap room ($${(status.capRoom / 1e6).toFixed(1)}M)`,
      description: 'Use available cap room to sign a free agent at any salary up to your room.',
      available: true,
      approxAmount: status.capRoom,
    });
    actions.push({
      id: 'use_room_exception',
      label: `Use Room Exception (~$${(cap * ROOM_EXCEPTION_PCT / 1e6).toFixed(1)}M)`,
      description: 'Room teams get a smaller exception after using their cap room.',
      available: true,
      approxAmount: cap * ROOM_EXCEPTION_PCT,
    });
  } else {
    // --- Over-cap exceptions ---
    // MLE — flavor depends on where the team sits relative to tax + aprons
    if (status.isOverSecondApron) {
      actions.push({
        id: 'use_mle',
        label: 'Use MLE',
        description: 'Mid-Level Exception is not available for teams over the second apron.',
        available: false,
        blockedReason: 'Team is over the second apron',
        approxAmount: 0,
      });
    } else if (status.isOverFirstApron) {
      const amount = cap * TAXPAYER_MLE_PCT;
      actions.push({
        id: 'use_mle_taxpayer',
        label: `Use Taxpayer MLE (~$${(amount / 1e6).toFixed(1)}M)`,
        description: 'First-apron teams can only use the smaller taxpayer MLE.',
        available: true,
        approxAmount: amount,
      });
    } else if (status.isOverTax) {
      const amount = cap * TAX_MLE_PCT;
      actions.push({
        id: 'use_mle_taxpayer',
        label: `Use Tax MLE (~$${(amount / 1e6).toFixed(1)}M)`,
        description: 'Tax-paying teams have access to a reduced MLE.',
        available: true,
        approxAmount: amount,
      });
    } else {
      const amount = cap * NON_TAX_MLE_PCT;
      actions.push({
        id: 'use_mle_nontax',
        label: `Use Non-Tax MLE (~$${(amount / 1e6).toFixed(1)}M)`,
        description: 'Full non-taxpayer mid-level exception (~9% of the cap).',
        available: true,
        approxAmount: amount,
      });
    }

    // BAE — blocked by first apron
    if (status.isOverFirstApron) {
      actions.push({
        id: 'use_bae',
        label: 'Use Bi-Annual Exception',
        description: 'BAE is unavailable above the first apron.',
        available: false,
        blockedReason: 'Team is over the first apron',
        approxAmount: 0,
      });
    } else {
      const amount = cap * BAE_PCT;
      actions.push({
        id: 'use_bae',
        label: `Use Bi-Annual Exception (~$${(amount / 1e6).toFixed(1)}M)`,
        description: 'Available every other year for teams under the first apron.',
        available: true,
        approxAmount: amount,
      });
    }
  }

  // --- Always-available actions ---
  actions.push({
    id: 'sign_minimum',
    label: 'Sign veteran minimum',
    description: 'Always available — no exception needed. Scales with the signee\'s years of service ($1.35M rookie → $3.87M 10-yr vet).',
    available: true,
    // Representative mid-career vet-minimum figure for the affordance display;
    // the actual charge is the signee's service-time minimum at signing.
    approxAmount: minimumSalary(4),
  });

  // Waive-and-stretch only if the team has at least one releasable contract
  const hasReleasable = teamPlayers.some(p => p.contract && p.contract.years.some(y => y.guaranteed && y.season >= season));
  if (hasReleasable) {
    actions.push({
      id: 'stretch_release',
      label: 'Waive and stretch a player',
      description: 'Spread remaining guaranteed money across (2N+1) years to reduce annual dead cap.',
      available: true,
    });
  }

  return actions;
}
