'use client';

import { useEffect } from 'react';
import { useGameStore } from '@/lib/engine/store';
import { GameShell } from '@/components/game/GameShell';
import { Card, CardHeader, CardTitle } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import Link from 'next/link';

function gradeColor(grade: string): string {
  if (grade.startsWith('A')) return 'text-green-600';
  if (grade.startsWith('B')) return 'text-blue-600';
  if (grade.startsWith('C')) return 'text-amber-600';
  return 'text-red-600';
}

function gradeBg(grade: string): string {
  if (grade.startsWith('A')) return 'bg-green-50 border-green-200';
  if (grade.startsWith('B')) return 'bg-blue-50 border-blue-200';
  if (grade.startsWith('C')) return 'bg-amber-50 border-amber-200';
  return 'bg-red-50 border-red-200';
}

const POSITION_NAMES: Record<string, string> = {
  QB: 'Quarterbacks',
  RB: 'Running Backs',
  WR: 'Wide Receivers',
  TE: 'Tight Ends',
  OL: 'Offensive Line',
  DL: 'Defensive Line',
  LB: 'Linebackers',
  CB: 'Cornerbacks',
  S: 'Safeties',
};

export default function DraftPreviewPage() {
  const { draftClassPreview, season, phase, week, leagueSettings, ensureDraftClassPreview, nflMockDraft, teams, userTeamId } = useGameStore();
  const tradeDeadline = leagueSettings?.tradeDeadlineWeek ?? 12;
  const isPreviewAvailable = draftClassPreview && draftClassPreview.season === season;
  const beforeDeadline = phase === 'regular' && week < tradeDeadline;

  // Auto-generate the preview when the user visits and they're past the deadline
  // (covers paths where simWeek wasn't called for week === deadline, e.g. simToWeek)
  useEffect(() => {
    if (!isPreviewAvailable && !beforeDeadline) {
      ensureDraftClassPreview();
    }
  }, [isPreviewAvailable, beforeDeadline, ensureDraftClassPreview]);

  return (
    <GameShell>
      <div className="max-w-4xl mx-auto space-y-4">
        <div>
          <h2 className="text-2xl font-black">Draft Class Preview</h2>
          <p className="text-sm text-[var(--text-sec)] mt-1">
            Position-by-position scouting report on the {season + 1} draft class.
            Generated by the BS Football war room.
          </p>
        </div>

        {!isPreviewAvailable && beforeDeadline && (
          <Card>
            <div className="text-center py-10">
              <div className="text-4xl mb-3">📋</div>
              <h3 className="text-lg font-bold mb-2">Scouting Report Not Yet Available</h3>
              <p className="text-sm text-[var(--text-sec)]">
                The draft class preview will be released after Week {tradeDeadline} (Trade Deadline).
              </p>
              <p className="text-xs text-[var(--text-sec)] mt-2">
                Currently Week {week} of the regular season.
              </p>
            </div>
          </Card>
        )}

        {!isPreviewAvailable && !beforeDeadline && (
          <Card>
            <div className="text-center py-10">
              <div className="text-4xl mb-3">📋</div>
              <h3 className="text-lg font-bold mb-2">No Preview Available</h3>
              <p className="text-sm text-[var(--text-sec)]">
                Sim past the trade deadline to generate the draft class preview.
              </p>
            </div>
          </Card>
        )}

        {isPreviewAvailable && (
          <>
            <Card>
              <CardHeader><CardTitle>Position Group Grades</CardTitle></CardHeader>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {draftClassPreview.groups.map(group => (
                  <div
                    key={group.position}
                    className={`flex items-center gap-3 p-3 rounded-lg border ${gradeBg(group.grade)}`}
                  >
                    <div className="shrink-0">
                      <Badge>{group.position}</Badge>
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-sm font-bold">{POSITION_NAMES[group.position] ?? group.position}</span>
                        <span className={`text-2xl font-black tabular-nums ${gradeColor(group.grade)}`}>{group.grade}</span>
                      </div>
                      <p className="text-xs text-[var(--text-sec)] mt-0.5 leading-tight">{group.depthNote}</p>
                      <div className="text-[10px] text-[var(--text-sec)] mt-1 tabular-nums">
                        Projected OVR range (top 10): <span className="font-bold text-[var(--text)]">{group.ovrLow}–{group.ovrHigh}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Card>

            {nflMockDraft && nflMockDraft.length > 0 && (
              <Card>
                <CardHeader><CardTitle>🔮 Round 1 Mock Projection</CardTitle></CardHeader>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="text-[var(--text-sec)] text-xs uppercase tracking-wider border-b border-[var(--border)]">
                        <th className="text-left pb-2 pl-2">#</th>
                        <th className="text-left pb-2">Team</th>
                        <th className="text-left pb-2">Projected Pick</th>
                        <th className="text-left pb-2 pr-2">Pos · School</th>
                      </tr>
                    </thead>
                    <tbody>
                      {nflMockDraft.map((mock) => {
                        const mockTeam = teams.find(t => t.abbreviation === mock.teamAbbr);
                        const isUserMock = mockTeam?.id === userTeamId;
                        return (
                          <tr key={mock.pickNum} className={`border-t border-[var(--border)] ${isUserMock ? 'bg-blue-50' : ''}`}>
                            <td className="py-2 pl-2 text-[var(--text-sec)] font-mono">{mock.pickNum}</td>
                            <td className="py-2 font-bold">{mockTeam?.abbreviation ?? mock.teamAbbr}</td>
                            <td className="py-2">
                              <span className="font-medium">{mock.firstName} {mock.lastName}</span>
                            </td>
                            <td className="py-2 pr-2 text-xs text-[var(--text-sec)]">{mock.position}{mock.college ? ` · ${mock.college}` : ''}</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </Card>
            )}

            <Card>
              <div className="text-xs text-[var(--text-sec)] italic">
                These grades reflect projected class quality at each position. Final draft order and individual player evaluations will be available when the draft begins. Use this report to plan trades, contract decisions, and positional needs heading into the offseason.
              </div>
            </Card>
          </>
        )}

        <div className="text-center pt-4">
          <Link href="/" className="text-sm text-blue-600 hover:underline">← Back to Dashboard</Link>
        </div>
      </div>
    </GameShell>
  );
}
