export {
  getInjuries,
  getPlayThrough,
  isInjuredOn,
  isPlayingThrough,
  canPlayThrough,
  playThroughInjury,
  healthyPlayers,
  clearHealed,
  rollGameInjuries,
  applyInjuryRolls,
  SEVERITY_LABEL,
  type InjuryRecord,
  type InjuryMap,
  type PlayThroughMap,
  type InjurySeverity,
} from './injuries';
